hostname: ${HOSTNAME:${HOST:${COMPUTERNAME:unknown}}}

server:
  port: 8080
  http2.enabled: on

jasypt.encryptor.password: ${JASYPT.KEY}

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: on

spring:
  threads.virtual.enabled: on
  jackson.time-zone: Asia/Seoul

  servlet.encoding:
    charset: UTF-8
    enabled: true
    force: true  # 응답 헤더에 강제로 UTF-8을 박아버립니다.

  config.import:
    - log.yml

  datasource:
    # 드라이버 클래스 (생략 가능, URL 보고 스프링이 자동 추론함)
    # driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB.URL}?sessionVariables=tx_isolation='READ-COMMITTED'&allowMultiQueries=true
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}

    # HikariCP 상세 설정 (스프링 부트 기본 커넥션 풀)
    hikari:
      connection-init-sql: select 1
      connection-test-query: select 1
      maximum-pool-size: 100
      minimum-idle: 1